### ISSUE TITLE
not support https?

### ISSUE THREAD

**Issue by aland-zhang** [silenceper/dcmp#1]
this is my config:

listen: "0.0.0.0:8000"

endpoints:    my etcd cluster setup  on 3 nodes ，the status is normal
- "https://10.1.236.104:2379"
- "https://10.1.236.105:2379"
- "https://10.1.236.106:2379"

open the first page http://10.1.236.104:8000
Show This Error " client: etcd cluster is unavailable or misconfigured" .

**Comment by silenceper** [comment]
ssl support in in this branch: [feature/ssl](https://github.com/silenceper/dcmp/tree/feature/ssl)
