### ISSUE TITLE
编译bug ，help

### ISSUE THREAD

**Issue by changyonggang** [silenceper/dcmp#15]
当我运行service.sh脚本时报错，如下：

`# github.com/coreos/etcd/pkg/transport
../go/lib/src/github.com/coreos/etcd/pkg/transport/listener.go:183: cfg.VerifyPeerCertificate undefined (type *tls.Config has no field or method VerifyPeerCertificate)
../go/lib/src/github.com/coreos/etcd/pkg/transport/listener.go:200: cfg.GetClientCertificate undefined (type *tls.Config has no field or method GetClientCertificate)
../go/lib/src/github.com/coreos/etcd/pkg/transport/listener.go:200: undefined: tls.CertificateRequestInfo
../go/lib/src/github.com/coreos/etcd/pkg/transport/listener_tls.go:233: undefined: net.DefaultResolver in net.DefaultResolver.LookupAddr
./service.sh:行2: ./bin/dcmp: 没有那个文件或目录`

**Comment by silenceper** [comment]
应该是依赖包版本的问题，该项目使用了govendor ，用`govendor sync`拉下来指定的版本到vendor目录中

**Comment by changyonggang** [comment]
谢谢，问题已经解决，需要用go 1.9版本编译，希望写到readme文件中。
