### ISSUE TITLE
undefined: validator.Config

### ISSUE THREAD

**Issue by gl328518397** [silenceper/dcmp#3]
sh service.sh
# github.com/gin-gonic/gin/binding
..\..\gin-gonic\gin\binding\default_validator.go:29: undefined: validator.Config
..\..\gin-gonic\gin\binding\default_validator.go:30: too many arguments in call to validator.New
service.sh: line 2: ./bin/dcmp: No such file or directory

**Comment by silenceper** [comment]
试试重新更新gin `go get -u  github.com/gin-gonic/gin`

**Comment by gl328518397** [comment]
您好，我是在windows上，有关系么

**Comment by gl328518397** [comment]
按照你说的方法试了还是不行。您看一下我的过程有问题么？
![qq 20161220134124](https://cloud.githubusercontent.com/assets/14244945/21339451/58c036b0-c6ba-11e6-9cd5-336bf6cda5fd.png)

**Comment by silenceper** [comment]
你这是相关依赖没有完全装好 ，错误信息不是很明显么。
翻墙/或者用`gopm`工具装好依赖

**Comment by gl328518397** [comment]
多谢。
