### ISSUE TITLE
默认etcd监控路径可以变么？

### ISSUE THREAD

**Issue by gl328518397** [silenceper/dcmp#7]
你好，我看默认是配置etcd上的这个路径  “/config”  可以修改成一个其他已经存在的路径么？

**Comment by silenceper** [comment]
目前不支持配置。
在这里变更：`https://github.com/silenceper/dcmp/blob/master/app.go#L26`

**Comment by gl328518397** [comment]
好的，多谢，如果配置成etcd.GetKeyList("/") 是不是可以监控整个etcd了？

**Comment by gl328518397** [comment]
你好，已经试过了，可以。多谢。
