### ISSUE TITLE
第一次启动时提示Key找不到（/config）

### ISSUE THREAD

**Issue by carryxyh** [silenceper/dcmp#9]
如题。启动时报错，左侧侧边栏里没有任何内容，请问怎么解决？
提示的信息:
100: Key not found (/config) [5]

**Comment by silenceper** [comment]
因为 我默认配置信息是读取的 /config这个目录下的，所以在etcd中建了 /config 目录就好了  。

这个问题已经fix了

**Comment by carryxyh** [comment]
thanks
